apiVersion: v1
kind: Service
metadata:
  name: golang-svc
spec:
  selector:
    app: sample-golang-app
  type: NodePort
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30082
