apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  selector:
    app: sample-node-app
  type: NodePort
  ports:
    - name: tcp
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30081
